spring:
  profiles: 
    active: test
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 10

server:
  error:
    include-stacktrace: never
    include-message: never

