spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5434/crudangulardb
    username: crudangular
    password: crudangularpass
    driver-class-name: org.postgresql.Driver
  devtools:
    add-properties: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
